# emoji reference: https://github.com/buildkite/emojis#emoji-reference
env:
  RELEASE_BRANCH: main
  GITHUB_TOKEN_NAME: "write"
  DOCS_DIR: "./docs/_build/html"
  UV_NATIVE_TLS: "true"
  UV_INDEX_URL: "https://artifactory.global.square/artifactory/api/pypi/block-pypi/simple"

steps:
  - group: llmit
    steps:
      - label: ":pipeline: Build Project & Run Tests"
        commands:
          - "echo '--- :package: Building Project Environment'"
          - "uv venv"
          - "uv sync --frozen --verbose"
          - echo '^^^ +++'
          - "echo '--- :pytest: Running Tests'"
          - "uv run pytest tests"
          - echo '^^^ +++'

      - wait

      - label: ":artifactory: Publish Package to Artifactory"
        branches: "main"
        commands:
          - "echo '--- :artifactory: Uploading to Artifactory'"
          - "mlkite artifactory-upload"  # https://github.com/squareup/mlkite/blob/main/mlkite-artifactory-upload
          - echo '^^^ +++'

      - label: ":books: Publish Documentation"
        branches: "main"
        commands:
          - "echo '--- :package: Building Project Environment'"
          - "uv venv"
          - "uv sync --frozen --verbose"
          - echo '^^^ +++'
          - "echo '--- :python: Building Documentation'"
          - "uv run mkdocs build"
          - "mkdir -p $DOCS_DIR"
          - "cp -r ./site/* $DOCS_DIR"
          - "rm -r uv.lock"  # needed to remove existing project directory so autodoc plays nice
          - "mlkite publish-docs ./docs"
          - echo '^^^ +++'
